name: Genrate TOC

on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  generate-toc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}

      - name: Genrate TOC
        run: ./toc-linux

      - uses: actions/upload-artifact@v2
        with:
          name: README.md
          path: README.md

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'docs: Update generated README'
          branch: master
